export var aryIannaTimeZones = [
     ['Europe/Andorra', 'Andorra'],
     ['Asia/Dubai', 'Dubai'],
     ['Asia/Kabul', 'Kabul'],
     ['Europe/Tirane', 'Tirane'],
     ['Asia/Yerevan', 'Yerevan'],
     ['Antarctica/Casey', 'Casey'],
     ['Antarctica/Davis', 'Davis'],
     ['Antarctica/DumontDUrville', 'DumontDUrville'], // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
     ['Antarctica/Mawson', 'Mawson'],
     ['Antarctica/Palmer', 'Palmer'],
     ['Antarctica/Rothera', 'Rothera'],
     ['Antarctica/Syowa', 'Syowa'],
     ['Antarctica/Troll', 'Troll'],
     ['Antarctica/Vostok', 'Vostok'],
     ['America/Argentina/Buenos_Aires', 'Argentina/Buenos Aires'],
     ['America/Argentina/Cordoba', 'Argentina/Cordoba'],
     ['America/Argentina/Salta', 'Argentina/Salta'],
     ['America/Argentina/Jujuy', 'Argentina/Jujuy'],
     ['America/Argentina/Tucuman', 'Argentina/Tucuman'],
     ['America/Argentina/Catamarca', 'Argentina/Catamarca'],
     ['America/Argentina/La_Rioja', 'Argentina/La Rioja'],
     ['America/Argentina/San_Juan', 'Argentina/San Juan'],
     ['America/Argentina/Mendoza', 'Argentina/Mendoza'],
     ['America/Argentina/San_Luis', 'Argentina/San Luis'],
     ['America/Argentina/Rio_Gallegos', 'Argentina/Rio Gallegos'],
     ['America/Argentina/Ushuaia', 'Argentina/Ushuaia'],
     ['Pacific/Pago_Pago', 'Pago Pago'],
     ['Europe/Vienna', 'Vienna'],
     ['Australia/Lord_Howe', 'Lord Howe'],
     ['Antarctica/Macquarie', 'Macquarie'],
     ['Australia/Hobart', 'Hobart'],
     ['Australia/Currie', 'Currie'],
     ['Australia/Melbourne', 'Melbourne'],
     ['Australia/Sydney', 'Sydney'],
     ['Australia/Broken_Hill', 'Broken Hill'],
     ['Australia/Brisbane', 'Brisbane'],
     ['Australia/Lindeman', 'Lindeman'],
     ['Australia/Adelaide', 'Adelaide'],
     ['Australia/Darwin', 'Darwin'],
     ['Australia/Perth', 'Perth'],
     ['Australia/Eucla', 'Eucla'],
     ['Asia/Baku', 'Baku'],
     ['America/Barbados', 'Barbados'],
     ['Asia/Dhaka', 'Dhaka'],
     ['Europe/Brussels', 'Brussels'],
     ['Europe/Sofia', 'Sofia'],
     ['Atlantic/Bermuda', 'Bermuda'],
     ['Asia/Brunei', 'Brunei'],
     ['America/La_Paz', 'La Paz'],
     ['America/Noronha', 'Noronha'],
     ['America/Belem', 'Belem'],
     ['America/Fortaleza', 'Fortaleza'],
     ['America/Recife', 'Recife'],
     ['America/Araguaina', 'Araguaina'],
     ['America/Maceio', 'Maceio'],
     ['America/Bahia', 'Bahia'],
     ['America/Sao_Paulo', 'Sao Paulo'],
     ['America/Campo_Grande', 'Campo Grande'],
     ['America/Cuiaba', 'Cuiaba'],
     ['America/Santarem', 'Santarem'],
     ['America/Porto_Velho', 'Porto Velho'],
     ['America/Boa_Vista', 'Boa Vista'],
     ['America/Manaus', 'Manaus'],
     ['America/Eirunepe', 'Eirunepe'],
     ['America/Rio_Branco', 'Rio Branco'],
     ['America/Nassau', 'Nassau'],
     ['Asia/Thimphu', 'Thimphu'],
     ['Europe/Minsk', 'Minsk'],
     ['America/Belize', 'Belize'],
     ['America/St_Johns', 'St Johns'],
     ['America/Halifax', 'Halifax'],
     ['America/Glace_Bay', 'Glace Bay'],
     ['America/Moncton', 'Moncton'],
     ['America/Goose_Bay', 'Goose Bay'],
     ['America/Blanc-Sablon', 'Blanc-Sablon'],
     ['America/Toronto', 'Toronto'],
     ['America/Nipigon', 'Nipigon'],
     ['America/Thunder_Bay', 'Thunder Bay'],
     ['America/Iqaluit', 'Iqaluit'],
     ['America/Pangnirtung', 'Pangnirtung'],
     ['America/Atikokan', 'Atikokan'],
     ['America/Winnipeg', 'Winnipeg'],
     ['America/Rainy_River', 'Rainy River'],
     ['America/Resolute', 'Resolute'],
     ['America/Rankin_Inlet', 'Rankin Inlet'],
     ['America/Regina', 'Regina'],
     ['America/Swift_Current', 'Swift Current'],
     ['America/Edmonton', 'Edmonton'],
     ['America/Cambridge_Bay', 'Cambridge Bay'],
     ['America/Yellowknife', 'Yellowknife'],
     ['America/Inuvik', 'Inuvik'],
     ['America/Creston', 'Creston'],
     ['America/Dawson_Creek', 'Dawson Creek'],
     ['America/Fort_Nelson', 'Fort Nelson'],
     ['America/Vancouver', 'Vancouver'],
     ['America/Whitehorse', 'Whitehorse'],
     ['America/Dawson', 'Dawson'],
     ['Indian/Cocos', 'Cocos'],
     ['Europe/Zurich', 'Zurich'],
     ['Africa/Abidjan', 'Abidjan'],
     ['Pacific/Rarotonga', 'Rarotonga'],
     ['America/Santiago', 'Santiago'],
     ['America/Punta_Arenas', 'Punta Arenas'],
     ['Pacific/Easter', 'Easter'],
     ['Asia/Shanghai', 'Shanghai'],
     ['Asia/Urumqi', 'Urumqi'],
     ['America/Bogota', 'Bogota'],
     ['America/Costa_Rica', 'Costa Rica'],
     ['America/Havana', 'Havana'],
     ['Atlantic/Cape_Verde', 'Cape Verde'],
     ['America/Curacao', 'Curacao'],
     ['Indian/Christmas', 'Christmas'],
     ['Asia/Nicosia', 'Nicosia'],
     ['Asia/Famagusta', 'Famagusta'],
     ['Europe/Prague', 'Prague'],
     ['Europe/Berlin', 'Berlin'],
     ['Europe/Copenhagen', 'Copenhagen'],
     ['America/Santo_Domingo', 'Santo Domingo'],
     ['Africa/Algiers', 'Algiers'],
     ['America/Guayaquil', 'Guayaquil'],
     ['Pacific/Galapagos', 'Galapagos'],
     ['Europe/Tallinn', 'Tallinn'],
     ['Africa/Cairo', 'Cairo'],
     ['Africa/El_Aaiun', 'El Aaiun'],
     ['Europe/Madrid', 'Madrid'],
     ['Africa/Ceuta', 'Ceuta'],
     ['Atlantic/Canary', 'Canary'],
     ['Europe/Helsinki', 'Helsinki'],
     ['Pacific/Fiji', 'Fiji'],
     ['Atlantic/Stanley', 'Stanley'],
     ['Pacific/Chuuk', 'Chuuk'],
     ['Pacific/Pohnpei', 'Pohnpei'],
     ['Pacific/Kosrae', 'Kosrae'],
     ['Atlantic/Faroe', 'Faroe'],
     ['Europe/Paris', 'Paris'],
     ['Europe/London', 'London'],
     ['Asia/Tbilisi', 'Tbilisi'],
     ['America/Cayenne', 'Cayenne'],
     ['Africa/Accra', 'Accra'],
     ['Europe/Gibraltar', 'Gibraltar'],
     ['America/Godthab', 'Godthab'],
     ['America/Danmarkshavn', 'Danmarkshavn'],
     ['America/Scoresbysund', 'Scoresbysund'],
     ['America/Thule', 'Thule'],
     ['Europe/Athens', 'Athens'],
     ['Atlantic/South_Georgia', 'South Georgia'],
     ['America/Guatemala', 'Guatemala'],
     ['Pacific/Guam', 'Guam'],
     ['Africa/Bissau', 'Bissau'],
     ['America/Guyana', 'Guyana'],
     ['Asia/Hong_Kong', 'Hong Kong'],
     ['America/Tegucigalpa', 'Tegucigalpa'],
     ['America/Port-au-Prince', 'Port-au-Prince'],
     ['Europe/Budapest', 'Budapest'],
     ['Asia/Jakarta', 'Jakarta'],
     ['Asia/Pontianak', 'Pontianak'],
     ['Asia/Makassar', 'Makassar'],
     ['Asia/Jayapura', 'Jayapura'],
     ['Europe/Dublin', 'Dublin'],
     ['Asia/Jerusalem', 'Jerusalem'],
     ['Asia/Kolkata', 'Kolkata'],
     ['Indian/Chagos', 'Chagos'],
     ['Asia/Baghdad', 'Baghdad'],
     ['Asia/Tehran', 'Tehran'],
     ['Atlantic/Reykjavik', 'Reykjavik'],
     ['Europe/Rome', 'Rome'],
     ['America/Jamaica', 'Jamaica'],
     ['Asia/Amman', 'Amman'],
     ['Asia/Tokyo', 'Tokyo'],
     ['Africa/Nairobi', 'Nairobi'],
     ['Asia/Bishkek', 'Bishkek'],
     ['Pacific/Tarawa', 'Tarawa'],
     ['Pacific/Enderbury', 'Enderbury'],
     ['Pacific/Kiritimati', 'Kiritimati'],
     ['Asia/Pyongyang', 'Pyongyang'],
     ['Asia/Seoul', 'Seoul'],
     ['Asia/Almaty', 'Almaty'],
     ['Asia/Qyzylorda', 'Qyzylorda'],
     ['Asia/Qostanay', 'Qostanay'], // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
     ['Asia/Aqtobe', 'Aqtobe'],
     ['Asia/Aqtau', 'Aqtau'],
     ['Asia/Atyrau', 'Atyrau'],
     ['Asia/Oral', 'Oral'],
     ['Asia/Beirut', 'Beirut'],
     ['Asia/Colombo', 'Colombo'],
     ['Africa/Monrovia', 'Monrovia'],
     ['Europe/Vilnius', 'Vilnius'],
     ['Europe/Luxembourg', 'Luxembourg'],
     ['Europe/Riga', 'Riga'],
     ['Africa/Tripoli', 'Tripoli'],
     ['Africa/Casablanca', 'Casablanca'],
     ['Europe/Monaco', 'Monaco'],
     ['Europe/Chisinau', 'Chisinau'],
     ['Pacific/Majuro', 'Majuro'],
     ['Pacific/Kwajalein', 'Kwajalein'],
     ['Asia/Yangon', 'Yangon'],
     ['Asia/Ulaanbaatar', 'Ulaanbaatar'],
     ['Asia/Hovd', 'Hovd'],
     ['Asia/Choibalsan', 'Choibalsan'],
     ['Asia/Macau', 'Macau'],
     ['America/Martinique', 'Martinique'],
     ['Europe/Malta', 'Malta'],
     ['Indian/Mauritius', 'Mauritius'],
     ['Indian/Maldives', 'Maldives'],
     ['America/Mexico_City', 'Mexico City'],
     ['America/Cancun', 'Cancun'],
     ['America/Merida', 'Merida'],
     ['America/Monterrey', 'Monterrey'],
     ['America/Matamoros', 'Matamoros'],
     ['America/Mazatlan', 'Mazatlan'],
     ['America/Chihuahua', 'Chihuahua'],
     ['America/Ojinaga', 'Ojinaga'],
     ['America/Hermosillo', 'Hermosillo'],
     ['America/Tijuana', 'Tijuana'],
     ['America/Bahia_Banderas', 'Bahia Banderas'],
     ['Asia/Kuala_Lumpur', 'Kuala Lumpur'],
     ['Asia/Kuching', 'Kuching'],
     ['Africa/Maputo', 'Maputo'],
     ['Africa/Windhoek', 'Windhoek'],
     ['Pacific/Noumea', 'Noumea'],
     ['Pacific/Norfolk', 'Norfolk'],
     ['Africa/Lagos', 'Lagos'],
     ['America/Managua', 'Managua'],
     ['Europe/Amsterdam', 'Amsterdam'],
     ['Europe/Oslo', 'Oslo'],
     ['Asia/Kathmandu', 'Kathmandu'],
     ['Pacific/Nauru', 'Nauru'],
     ['Pacific/Niue', 'Niue'],
     ['Pacific/Auckland', 'Auckland'],
     ['Pacific/Chatham', 'Chatham'],
     ['America/Panama', 'Panama'],
     ['America/Lima', 'Lima'],
     ['Pacific/Tahiti', 'Tahiti'],
     ['Pacific/Marquesas', 'Marquesas'],
     ['Pacific/Gambier', 'Gambier'],
     ['Pacific/Port_Moresby', 'Port Moresby'],
     ['Pacific/Bougainville', 'Bougainville'],
     ['Asia/Manila', 'Manila'],
     ['Asia/Karachi', 'Karachi'],
     ['Europe/Warsaw', 'Warsaw'],
     ['America/Miquelon', 'Miquelon'],
     ['Pacific/Pitcairn', 'Pitcairn'],
     ['America/Puerto_Rico', 'Puerto Rico'],
     ['Asia/Gaza', 'Gaza'],
     ['Asia/Hebron', 'Hebron'],
     ['Europe/Lisbon', 'Lisbon'],
     ['Atlantic/Madeira', 'Madeira'],
     ['Atlantic/Azores', 'Azores'],
     ['Pacific/Palau', 'Palau'],
     ['America/Asuncion', 'Asuncion'],
     ['Asia/Qatar', 'Qatar'],
     ['Indian/Reunion', 'Reunion'],
     ['Europe/Bucharest', 'Bucharest'],
     ['Europe/Belgrade', 'Belgrade'],
     ['Europe/Kaliningrad', 'Kaliningrad'],
     ['Europe/Moscow', 'Moscow'],
     ['Europe/Simferopol', 'Simferopol'],
     ['Europe/Kirov', 'Kirov'],
     ['Europe/Astrakhan', 'Astrakhan'],
     ['Europe/Volgograd', 'Volgograd'],
     ['Europe/Saratov', 'Saratov'],
     ['Europe/Ulyanovsk', 'Ulyanovsk'],
     ['Europe/Samara', 'Samara'],
     ['Asia/Yekaterinburg', 'Yekaterinburg'],
     ['Asia/Omsk', 'Omsk'],
     ['Asia/Novosibirsk', 'Novosibirsk'],
     ['Asia/Barnaul', 'Barnaul'],
     ['Asia/Tomsk', 'Tomsk'],
     ['Asia/Novokuznetsk', 'Novokuznetsk'],
     ['Asia/Krasnoyarsk', 'Krasnoyarsk'],
     ['Asia/Irkutsk', 'Irkutsk'],
     ['Asia/Chita', 'Chita'],
     ['Asia/Yakutsk', 'Yakutsk'],
     ['Asia/Khandyga', 'Khandyga'],
     ['Asia/Vladivostok', 'Vladivostok'],
     ['Asia/Ust-Nera', 'Ust-Nera'],
     ['Asia/Magadan', 'Magadan'],
     ['Asia/Sakhalin', 'Sakhalin'],
     ['Asia/Srednekolymsk', 'Srednekolymsk'],
     ['Asia/Kamchatka', 'Kamchatka'],
     ['Asia/Anadyr', 'Anadyr'],
     ['Asia/Riyadh', 'Riyadh'],
     ['Pacific/Guadalcanal', 'Guadalcanal'],
     ['Indian/Mahe', 'Mahe'],
     ['Africa/Khartoum', 'Khartoum'],
     ['Europe/Stockholm', 'Stockholm'],
     ['Asia/Singapore', 'Singapore'],
     ['America/Paramaribo', 'Paramaribo'],
     ['Africa/Juba', 'Juba'],
     ['Africa/Sao_Tome', 'Sao Tome'],
     ['America/El_Salvador', 'El Salvador'],
     ['Asia/Damascus', 'Damascus'],
     ['America/Grand_Turk', 'Grand Turk'],
     ['Africa/Ndjamena', 'Ndjamena'],
     ['Indian/Kerguelen', 'Kerguelen'],
     ['Asia/Bangkok', 'Bangkok'],
     ['Asia/Dushanbe', 'Dushanbe'],
     ['Pacific/Fakaofo', 'Fakaofo'],
     ['Asia/Dili', 'Dili'],
     ['Asia/Ashgabat', 'Ashgabat'],
     ['Africa/Tunis', 'Tunis'],
     ['Pacific/Tongatapu', 'Tongatapu'],
     ['Europe/Istanbul', 'Istanbul'],
     ['America/Port_of_Spain', 'Port of Spain'],
     ['Pacific/Funafuti', 'Funafuti'],
     ['Asia/Taipei', 'Taipei'],
     ['Europe/Kiev', 'Kiev'],
     ['Europe/Uzhgorod', 'Uzhgorod'],
     ['Europe/Zaporozhye', 'Zaporozhye'],
     ['Pacific/Wake', 'Wake'],
     ['America/New_York', 'New York'],
     ['America/Detroit', 'Detroit'],
     ['America/Kentucky/Louisville', 'Kentucky/Louisville'],
     ['America/Kentucky/Monticello', 'Kentucky/Monticello'],
     ['America/Indiana/Indianapolis', 'Indiana/Indianapolis'],
     ['America/Indiana/Vincennes', 'Indiana/Vincennes'],
     ['America/Indiana/Winamac', 'Indiana/Winamac'],
     ['America/Indiana/Marengo', 'Indiana/Marengo'],
     ['America/Indiana/Petersburg', 'Indiana/Petersburg'],
     ['America/Indiana/Vevay', 'Indiana/Vevay'],
     ['America/Chicago', 'Chicago'],
     ['America/Indiana/Tell_City', 'Indiana/Tell City'],
     ['America/Indiana/Knox', 'Indiana/Knox'],
     ['America/Menominee', 'Menominee'],
     ['America/North_Dakota/Center', 'North Dakota/Center'],
     ['America/North_Dakota/New_Salem', 'North Dakota/New Salem'],
     ['America/North_Dakota/Beulah', 'North Dakota/Beulah'],
     ['America/Denver', 'Denver'],
     ['America/Boise', 'Boise'],
     ['America/Phoenix', 'Phoenix'],
     ['America/Los_Angeles', 'Los Angeles'],
     ['America/Anchorage', 'Anchorage'],
     ['America/Juneau', 'Juneau'],
     ['America/Sitka', 'Sitka'],
     ['America/Metlakatla', 'Metlakatla'],
     ['America/Yakutat', 'Yakutat'],
     ['America/Nome', 'Nome'],
     ['America/Adak', 'Adak'],
     ['Pacific/Honolulu', 'Honolulu'],
     ['America/Montevideo', 'Montevideo'],
     ['Asia/Samarkand', 'Samarkand'],
     ['Asia/Tashkent', 'Tashkent'],
     ['America/Caracas', 'Caracas'],
     ['Asia/Ho_Chi_Minh', 'Ho Chi Minh'],
     ['Pacific/Efate', 'Efate'],
     ['Pacific/Wallis', 'Wallis'],
     ['Pacific/Apia', 'Apia'],
     ['Africa/Johannesburg', 'Johannesburg']
   ];
   
let date = new Date;

console.log("-- BEGIN TIMEZONE CHECK SEQUENCE --");
aryIannaTimeZones.forEach((timeZone) => {   
     let strTime = date.toLocaleString("en-US", {
          timeZone: `${timeZone[0]}`
     });
     console.log(timeZone[0], strTime);
});
console.log("-- END TIMEZONE CHECK SEQUENCE --");